### ISSUE TITLE
Topic-Level Authorization

### ISSUE THREAD

**Issue by wmunyan** [opendxl/opendxl-client-java#12]
The wiki indicates:
`The fabric also supports topic-level authorization wherein individual topics can be restricted in terms of which clients can publish messages to and which clients can receive messages on a particular topic.`

Where/How is this topic-level authorization configured?

**Comment by tmcdonal** [comment]
Topic authorization must be configured within the OpenDXL Broker configuration files. 

See [OpenDXL Broker topicauth.policy](https://github.com/opendxl/opendxl-broker/wiki/topicauth.policy) for more details.
